# Generated by Django 3.2.6 on 2021-08-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universiteler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
                ('kodu', models.CharField(max_length=10)),
                ('akts', models.PositiveSmallIntegerField()),
                ('icerik', models.TextField()),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universiteler.bolumler')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universiteler.universite')),
            ],
        ),
    ]
