# Generated by Django 3.2.6 on 2021-08-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universiteler', '0002_ders'),
    ]

    operations = [
        migrations.AddField(
            model_name='ders',
            name='muafMi',
            field=models.BooleanField(null=True),
        ),
    ]
