# Generated by Django 3.2.6 on 2021-08-06 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universiteler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10)),
                ('sonuclandiMi', models.BooleanField(default=False)),
                ('zaman', models.DateTimeField(default=django.utils.timezone.now)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universiteler.bolumler')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universiteler.universite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
