# Generated by Django 3.2.6 on 2021-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universiteler', '0002_ders'),
        ('ogrenciler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='dersler',
            field=models.ManyToManyField(blank=True, null=True, to='universiteler.Ders'),
        ),
    ]
